### ISSUE TITLE
Crash with Discord v80

### ISSUE THREAD

**Issue by AfterCool** [brendonjkding/VolumeMixer#7]
Hi all :D
First of all thank you for your application which is great and fills a gap on iOS.

I'm here to report a bug that causes volume mixer, indeed when I updated Discord v80 it crashes instantly during a call, namely that on the version of Discord v47 there is no conflict with volume mixer.

I don't know if you can or want to fix this problem, but if you could fix it I would be very grateful :)

(I am running iOS 14.0.1)
Regard,
Smaïn,

**Comment by brendonjkding** [comment]
Just pushed a new version 0.0.5~beta1 to my repo. It should fix the crash issue. But I'm not sure if there is other issue because I'm not using audio in Discord.

**Comment by AfterCool** [comment]
It works with version 80 now, thanks a lot for your help :)
